export const serviceEscrowEventAbi = [
  {
    type: "event",
    name: "PlatformFeeUpdated",
    anonymous: false,
    inputs: [
      { name: "previousFeeBps", type: "uint256", indexed: false },
      { name: "newFeeBps", type: "uint256", indexed: false },
      { name: "actor", type: "address", indexed: true },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeeTreasuryUpdated",
    anonymous: false,
    inputs: [
      { name: "previousTreasury", type: "address", indexed: true },
      { name: "newTreasury", type: "address", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderCreated",
    anonymous: false,
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "subscriptionId", type: "uint256", indexed: false },
      { name: "serviceId", type: "uint256", indexed: false },
      { name: "amountPaid", type: "uint256", indexed: false },
      { name: "platformFeeAmount", type: "uint256", indexed: false },
      { name: "agentPayoutAmount", type: "uint256", indexed: false },
      { name: "status", type: "uint8", indexed: false },
      { name: "createdAt", type: "uint64", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderStatusChanged",
    anonymous: false,
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "previousStatus", type: "uint8", indexed: false },
      { name: "newStatus", type: "uint8", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DeliverySubmitted",
    anonymous: false,
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "deliveryRef", type: "string", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FundsReleased",
    anonymous: false,
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "agentTreasury", type: "address", indexed: true },
      { name: "customer", type: "address", indexed: false },
      { name: "feeTreasury", type: "address", indexed: false },
      { name: "platformFeeAmount", type: "uint256", indexed: false },
      { name: "agentPayoutAmount", type: "uint256", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Refunded",
    anonymous: false,
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "actor", type: "address", indexed: false },
      { name: "amountRefunded", type: "uint256", indexed: false },
      { name: "previousStatus", type: "uint8", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubscriptionCreated",
    anonymous: false,
    inputs: [
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "subscriber", type: "address", indexed: true },
      { name: "serviceId", type: "uint256", indexed: false },
      { name: "initialOrderId", type: "uint256", indexed: false },
      { name: "billingInterval", type: "uint8", indexed: false },
      { name: "recurringPrice", type: "uint256", indexed: false },
      { name: "active", type: "bool", indexed: false },
      { name: "createdAt", type: "uint64", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubscriptionStatusChanged",
    anonymous: false,
    inputs: [
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "active", type: "bool", indexed: false },
      { name: "updatedAt", type: "uint64", indexed: false },
    ],
  },
] as const;
